spring:
  servlet:
    multipart:
      file-size-threshold: 2048
      max-file-size: 5MB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  security:
    jwt:
      secret: ${JWT_SECRET_PHRASE}
      expired: 3600000
  main:
    banner-mode: "off"
management:
  endpoint:
    web:
      exposure:
        include: health, info
logging:
  level:
    root: info
    by.itacademy.profiler: debug
image:
  storage-dir: ${IMAGES_STORAGE_FOLDER}
curriculum-vitae:
  number-of-user-curriculum-vitae: 5
